development:
  adapter: postgresql
  encoding: unicode
  database: my_db
  pool: 5
  username: aloha
  password: aloha
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: my_db_prod
  pool: 5
  username: aloha
  password: aloha
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: my_db_test
  pool: 5
  username: aloha
  password: aloha
  host: localhost